-- Add tipo to liquidaciones_sueldo and update unique constraint
ALTER TABLE app.liquidaciones_sueldo
  ADD COLUMN IF NOT EXISTS tipo VARCHAR(20) NOT NULL DEFAULT 'mensual'
  CHECK (tipo IN ('mensual', 'sac_1', 'sac_2', 'indemnizacion'));

-- Drop old unique constraint (name auto-generated by postgres)
DO $$
DECLARE con text;
BEGIN
  SELECT conname INTO con
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'app' AND t.relname = 'liquidaciones_sueldo' AND c.contype = 'u';
  IF con IS NOT NULL THEN
    EXECUTE 'ALTER TABLE app.liquidaciones_sueldo DROP CONSTRAINT ' || con;
  END IF;
END $$;

ALTER TABLE app.liquidaciones_sueldo
  ADD CONSTRAINT liquidaciones_sueldo_empleado_periodo_tipo_key
  UNIQUE (empleado_id, periodo, tipo);

-- Add egreso fields to empleados_edificio
ALTER TABLE app.empleados_edificio
  ADD COLUMN IF NOT EXISTS fecha_egreso DATE,
  ADD COLUMN IF NOT EXISTS tipo_egreso VARCHAR(30)
    CHECK (tipo_egreso IN ('despido_sin_causa', 'despido_con_causa', 'renuncia', 'mutuo_acuerdo', 'muerte', 'jubilacion'));
